Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2023-04, with the labels that each got.

#596 [Aqara] Pet Feeder Edge Device Driver
  drivers/Aqara/aqara-feeder/config.yml
  drivers/Aqara/aqara-feeder/fingerprints.yml
  drivers/Aqara/aqara-feeder/profiles/aqara-pet-feeder.yml
  drivers/Aqara/aqara-feeder/src/init.lua
  drivers/Aqara/aqara-feeder/src/test/test_aqara_pet_feeder.lua
Labels: do not merge, needs invite link

#660 Unit test coverage based on matter cert test case audit
  drivers/SmartThings/matter-lock/src/init.lua
  drivers/SmartThings/matter-lock/src/test/test_matter_lock.lua
  drivers/SmartThings/matter-lock/src/test/test_matter_lock_codes.lua
  drivers/SmartThings/matter-lock/src/test/test_matter_lock_cota.lua
  drivers/SmartThings/matter-media/fingerprints.yml
  drivers/SmartThings/matter-media/src/init.lua
  drivers/SmartThings/matter-media/src/test/test_matter_media_speaker.lua
  drivers/SmartThings/matter-media/src/test/test_matter_media_video_player.lua
  drivers/SmartThings/matter-sensor/src/init.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/src/init.lua
  drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
  drivers/SmartThings/matter-window-covering/src/init.lua
  drivers/SmartThings/matter-window-covering/src/test/test_matter_window_covering.lua
Labels: workinprogress

#554 [Aqara] Aqara Smart Dimmer Controller T1 Pro
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/profiles/aqara-light.yml
  drivers/SmartThings/zigbee-switch/src/aqara-light/init.lua
  drivers/SmartThings/zigbee-switch/src/init.lua
  drivers/SmartThings/zigbee-switch/src/preferences.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_light.lua
Labels: do not merge
