Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2023-11, with the labels that each got.

#963 [Aqara] Smart Wall Switch(With Neutral, No Neutral)
  drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_power.lua
Labels: do not merge, WWST

#1053 Assure 2 Biometric 410
  drivers/SmartThings/zwave-lock/fingerprints.yml
Labels: WWST, Edge Builder Tool

#1051 WWST CERT for Yale Assure 2 Bio 430
  drivers/SmartThings/zwave-lock/fingerprints.yml
Labels: WWST, Edge Builder Tool

#891 Yale-700
  drivers/SmartThings/zwave-lock/fingerprints.yml
Labels: WWST

#1052 Yale-Assure-2-Bio-450
  drivers/SmartThings/zwave-lock/fingerprints.yml
Labels: do not merge, WWST, Edge Builder Tool

#1014 [Aqara] Aqara Motion Sensor P1
  drivers/SmartThings/zigbee-motion-sensor/fingerprints.yml
  drivers/SmartThings/zigbee-motion-sensor/src/aqara/init.lua
Labels: WWST

#981 wallhero add model ACL-401S2I
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/wallhero/init.lua
Labels: WWST

#980 wallhero add model ACL-401S3I
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/wallhero/init.lua
Labels: WWST

#982 wallhero add model ACL-401S1I
  drivers/SmartThings/zigbee-switch/fingerprints.yml
Labels: WWST

#983 wallhero add model ACL-401ON
  drivers/SmartThings/zigbee-switch/fingerprints.yml
Labels: WWST

#869 Nuki Smart Lock Pro
  drivers/SmartThings/matter-lock/fingerprints.yml
Labels: WWST

#953 WiZ A19 Matter
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/profiles/light-color-level-2200K-6500K.yml
Labels: WWST

#784 TLJ Door Lock fingerprint
  drivers/SmartThings/zwave-lock/fingerprints.yml
Labels: WWST
