Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-08, with the labels that each got.

#1411 New Devices (AiDot Matter Color Temperature Light) for Certification
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/profiles/light-level-colorTemperature-2700K-6500K.yml
Labels: WWST

#1520 New Device (Matter Thermostat) Eve Thermostat
  drivers/SmartThings/matter-thermostat/fingerprints.yml
Labels: WWST

#1536 Add support for the Extractor Hood Matter 1.3 device type
  drivers/SmartThings/matter-appliance/fingerprints.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-ac-wind.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-ac.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-hepa-ac-wind.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-hepa-ac.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-hepa-wind.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-hepa.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood-wind.yml
  drivers/SmartThings/matter-appliance/profiles/extractor-hood.yml
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/init.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/server/attributes/AttributeList.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/server/attributes/ChangeIndication.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/server/attributes/Condition.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/server/attributes/init.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/types/ChangeIndicationEnum.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/types/Feature.lua
  drivers/SmartThings/matter-appliance/src/ActivatedCarbonFilterMonitoring/types/init.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/init.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/server/attributes/AttributeList.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/server/attributes/ChangeIndication.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/server/attributes/Condition.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/server/attributes/init.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/types/ChangeIndicationEnum.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/types/Feature.lua
  drivers/SmartThings/matter-appliance/src/HepaFilterMonitoring/types/init.lua
  drivers/SmartThings/matter-appliance/src/embedded-cluster-utils.lua
  drivers/SmartThings/matter-appliance/src/init.lua
  drivers/SmartThings/matter-appliance/src/matter-extractor-hood/init.lua
  drivers/SmartThings/matter-appliance/src/test/test_matter_extractor_hood.lua
Labels: workinprogress

#1468 New Device (Matter Switch) Cync Indoor Plug CPLGSTDBLW1MS
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: do not merge, WWST

#1557 New Device (Matter Lock) Aqara U300
  drivers/SmartThings/matter-lock/fingerprints.yml
  drivers/SmartThings/matter-lock/src/aqara-lock/init.lua
Labels: WWST

#1604 Add shinasystem's full buttons switch for wwst
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
Labels: WWST

#1597 Update tests to account for default native handler registration
  drivers/SmartThings/matter-switch/src/test/test_eve_energy.lua
  drivers/SmartThings/matter-switch/src/test/test_light_illuminance_motion.lua
  drivers/SmartThings/matter-switch/src/test/test_matter_switch.lua
  drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_lights.lua
  drivers/SmartThings/matter-switch/src/test/test_multi_switch_parent_child_plugs.lua
  drivers/SmartThings/zigbee-switch/src/test/test_all_capability_zigbee_bulb.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_smart_plug_t1.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_module.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_module_no_power.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_no_power.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_switch_power.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aqara_wall_switch.lua
  drivers/SmartThings/zigbee-switch/src/test/test_aurora_relay.lua
  drivers/SmartThings/zigbee-switch/src/test/test_enbrighten_metering_dimmer.lua
  drivers/SmartThings/zigbee-switch/src/test/test_hanssem_switch.lua
  drivers/SmartThings/zigbee-switch/src/test/test_jasco_switch.lua
  drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_no_master.lua
  drivers/SmartThings/zigbee-switch/src/test/test_multi_switch_power.lua
  drivers/SmartThings/zigbee-switch/src/test/test_on_off_zigbee_bulb.lua
  drivers/SmartThings/zigbee-switch/src/test/test_robb_smarrt_2-wire_dimmer.lua
  drivers/SmartThings/zigbee-switch/src/test/test_robb_smarrt_knob_dimmer.lua
  drivers/SmartThings/zigbee-switch/src/test/test_wallhero_switch.lua
  drivers/SmartThings/zigbee-switch/src/test/test_zigbee_dimmer_power_energy.lua
  drivers/SmartThings/zigbee-switch/src/test/test_zigbee_ezex_switch.lua
  drivers/SmartThings/zwave-bulb/src/test/test_aeon_multiwhite_bulb.lua
  drivers/SmartThings/zwave-bulb/src/test/test_zwave_bulb.lua
  drivers/SmartThings/zwave-switch/src/test/test_aeotec_dimmer_switch.lua
  drivers/SmartThings/zwave-switch/src/test/test_aeotec_heavy_duty_switch.lua
  drivers/SmartThings/zwave-switch/src/test/test_aeotec_nano_dimmer.lua
  drivers/SmartThings/zwave-switch/src/test/test_fibaro_walli_double_switch.lua
  drivers/SmartThings/zwave-switch/src/test/test_generic_zwave_device1.lua
  drivers/SmartThings/zwave-switch/src/test/test_multi_metering_switch.lua
  drivers/SmartThings/zwave-switch/src/test/test_qubino_din_dimmer.lua
  drivers/SmartThings/zwave-switch/src/test/test_qubino_flush_dimmer.lua
  drivers/SmartThings/zwave-switch/src/test/test_qubino_temperature_sensor_with_power.lua
  drivers/SmartThings/zwave-switch/src/test/test_qubino_temperature_sensor_without_power.lua
  drivers/SmartThings/zwave-switch/src/test/test_wyfy_touch.lua
  drivers/SmartThings/zwave-switch/src/test/test_zooz_double_plug.lua
  drivers/SmartThings/zwave-switch/src/test/test_zooz_zen_30_dimmer_relay.lua
  drivers/SmartThings/zwave-switch/src/test/test_zwave_dimmer_power_energy.lua
  drivers/SmartThings/zwave-switch/src/test/test_zwave_dual_switch.lua
  drivers/SmartThings/zwave-switch/src/test/test_zwave_switch.lua
Labels: do not merge

#1457 Aqara Curtain Driver E1
  drivers/SmartThings/zigbee-window-treatment/capabilities/chargingState.yaml
  drivers/SmartThings/zigbee-window-treatment/capabilities/hookLockState.yaml
  drivers/SmartThings/zigbee-window-treatment/fingerprints.yml
  drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-aqara-curtain-driver-e1.yml
  drivers/SmartThings/zigbee-window-treatment/src/aqara/aqara_utils.lua
  drivers/SmartThings/zigbee-window-treatment/src/aqara/curtain-driver-e1/init.lua
  drivers/SmartThings/zigbee-window-treatment/src/aqara/init.lua
  drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_aqara_curtain_driver_e1.lua
Labels: do not merge, WWST
