Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-12, with the labels that each got.

#1750 Add Zemismart ZM25C Curtain Motor
  drivers/SmartThings/matter-window-covering/fingerprints.yml
Labels: do not merge, WWST

#1748 Add shinasystem's full buttons switch for wwst
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
Labels: WWST

#1794 New Devices (Matter Switch + Matter Sensor) 1 Heiman Co Sensor and 2 Zemismart Devices
  drivers/SmartThings/matter-sensor/fingerprints.yml
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1784 Add Zemismart Zm02 Curtian Motor
  drivers/SmartThings/matter-window-covering/fingerprints.yml
Labels: WWST

#1781 New Devices (Matter Switch) Aqara Bulbs
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1804 New Device (Matter Switch) U Tec Bulb
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1815 New Device (Matter Sensor + Matter Switch) Neo
  drivers/SmartThings/matter-sensor/fingerprints.yml
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST, ATS

#1841 modified cn.csv and fingerprints
  drivers/SmartThings/matter-window-covering/fingerprints.yml
  tools/localizations/cn.csv
Labels: WWST

#1836 Add device WISTAR WSERD30-B Smart Tubular Motor
  drivers/SmartThings/matter-window-covering/fingerprints.yml
  tools/localizations/cn.csv
Labels: WWST

#1838 Add devices WISTAR WSER50 Smart Tubular Motor
  drivers/SmartThings/matter-window-covering/fingerprints.yml
Labels: WWST

#1837 Add devices WISTAR WSER40 Smart Tubular Motor
  drivers/SmartThings/matter-window-covering/fingerprints.yml
Labels: WWST
