Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-06, with the labels that each got.

#1223 Matter Thermostat: Heat/cool setpoint and temp limits dynamic constraints
  drivers/SmartThings/matter-thermostat/src/init.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits_rpc.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua
Labels: commit squashing required

#1224 Matter Sensor: Temp limits dynamic constraints
  drivers/SmartThings/matter-sensor/src/init.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_rpc.lua
Labels: commit squashing required

#1274 New Device (Z-Wave Window Treatment) RYSE SmartShade
  drivers/SmartThings/zwave-window-treatment/fingerprints.yml
Labels: do not merge, WWST

#1413 Add a matter-lock driver for Aqara
  drivers/SmartThings/matter-lock/fingerprints.yml
  drivers/SmartThings/matter-lock/profiles/lock-lockalarm-nobattery.yml
  drivers/SmartThings/matter-lock/profiles/lock-lockalarm.yml
  drivers/SmartThings/matter-lock/src/init.lua
  drivers/SmartThings/matter-lock/src/test/test_aqara_matter_lock.lua
Labels: do not merge

#1431 Add fingerprints of TOTEM Door Lock for SmartThingsEdgeDriver
  drivers/SmartThings/zigbee-lock/fingerprints.yml
  tools/localizations/cn.csv
Labels: do not merge

#1331 New Device (Matter Sensor) Aqara Motion and Light Sensor P2
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: do not merge, WWST

#1346 New Device (Matter Switch) Linkind Smart Plug
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1464 New Device (Matter Switch) NanoLeaf Smart Holiday String Lights
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1421 New Device (Matter Switch) 20ECE4101
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1419 Screen Innovations window-shade Zigbee driver
  drivers/SmartThings/zigbee-window-treatment/fingerprints.yml
  drivers/SmartThings/zigbee-window-treatment/profiles/window-treatment-powerSource.yml
  drivers/SmartThings/zigbee-window-treatment/src/init.lua
  drivers/SmartThings/zigbee-window-treatment/src/screen-innovations/init.lua
  drivers/SmartThings/zigbee-window-treatment/src/test/test_zigbee_window_treatment_screen_innovations.lua
Labels: WWST
