Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-03, with the labels that each got.

#1121 new device (Matter Window Covering): WWST Cert request to add the Zemismart MT25B, MT82, MT25A, ZM25M
  drivers/SmartThings/matter-window-covering/fingerprints.yml
Labels: do not merge, WWST

#1232 New Device (Matter-Switch) Cync Bulbs 1.01.170
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1115 Create to Zigbee fan for SLED
  drivers/SmartThings/zigbee-fan/config.yml
  drivers/SmartThings/zigbee-fan/fingerprints.yml
  drivers/SmartThings/zigbee-fan/profiles/fan-light.yml
  drivers/SmartThings/zigbee-fan/src/configurations.lua
  drivers/SmartThings/zigbee-fan/src/fan-light/init.lua
  drivers/SmartThings/zigbee-fan/src/init.lua
  drivers/SmartThings/zigbee-fan/src/test/test_fan_light.lua
Labels: WWST

#1160 Aqara Smart Natural Gas Detector
  drivers/SmartThings/zigbee-smoke-detector/capabilities/lifeTimeReport.yaml
  drivers/SmartThings/zigbee-smoke-detector/capabilities/sensitivityAdjustment.yaml
  drivers/SmartThings/zigbee-smoke-detector/fingerprints.yml
  drivers/SmartThings/zigbee-smoke-detector/profiles/gas-lifetime-selfcheck-aqara.yml
  drivers/SmartThings/zigbee-smoke-detector/src/aqara-gas/init.lua
  drivers/SmartThings/zigbee-smoke-detector/src/init.lua
  drivers/SmartThings/zigbee-smoke-detector/src/test/test_aqara_gas_detector.lua
Labels: WWST

#1048 Add ThirdReality Driver for Matter Night Light
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/profiles/light-color-level-illuminance-motion-1000K-15000K.yml
  drivers/SmartThings/matter-switch/profiles/light-color-level-illuminance-motion.yml
  drivers/SmartThings/matter-switch/src/init.lua
  drivers/SmartThings/matter-switch/src/test/test_light_illuminance_motion.lua
Labels: do not merge, commit squashing required, WWST

#1193 New Devices (Z-Wave Switch): Smart Plugs
  drivers/SmartThings/zwave-switch/fingerprints.yml
Labels: do not merge, WWST

#1249 Aqara Wireless Remote Switch E1 (Single Rocker)
  drivers/SmartThings/zigbee-button/fingerprints.yml
  drivers/SmartThings/zigbee-button/src/aqara/init.lua
  drivers/SmartThings/zigbee-button/src/test/test_aqara_button.lua
Labels: do not merge, WWST

#724 add rgbw,dimming light and water sensor
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/rgbw-bulb/init.lua
  drivers/SmartThings/zigbee-switch/src/zigbee-dimming-light/init.lua
  drivers/SmartThings/zigbee-water-leak-sensor/fingerprints.yml
  drivers/SmartThings/zigbee-water-leak-sensor/src/init.lua
  drivers/SmartThings/zigbee-water-leak-sensor/src/sengled/init.lua
  drivers/SmartThings/zigbee-water-leak-sensor/src/test/test_sengled_water_leak_sensor.lua
Labels: WWST
