Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-07, with the labels that each got.

#1459 New Device (Matter Switch) Zemismart ZM606-3
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1477 Add TOTEM P90
  drivers/SmartThings/zigbee-lock/fingerprints.yml
Labels: WWST

#1504 Matter Switch: Add Nanoleaf Essentials Wifi Bulb fingerprint
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1512 Matter Switch: new device Linkind Smart Light Bulb A21 RGBTW 1600lm
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1522 New Device (Matter Switch) Cync Full Color Deco
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1058 Edge Driver Repo Check List
  .github/PULL_REQUEST_TEMPLATE.md
Labels: do not merge

#1528 Remove embedded clusters from CI coverage results
  tools/config.luacov
Labels: commit squashing required

#1530 New Device (Matter Switch) Orein OS0100411267
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1531 New Devices (Matter Switch) Cync Bulbs and Winees Plug
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1455 Revert dynamic constraint updates for matter-thermostat and matter-sensor
  drivers/SmartThings/matter-sensor/src/init.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_air_quality_sensor.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_featuremap.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_sensor_rpc.lua
  drivers/SmartThings/matter-sensor/src/test/test_matter_smoke_co_alarm.lua
  drivers/SmartThings/matter-thermostat/src/init.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_air_purifier.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_room_ac.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_featuremap.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermo_setpoint_limits_rpc.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat.lua
  drivers/SmartThings/matter-thermostat/src/test/test_matter_thermostat_composed_bridged.lua
Labels: commit squashing required
