Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-09, with the labels that each got.

#1454 Aqara Smart Radiator Thermostat E1
  drivers/SmartThings/zigbee-thermostat/capabilities/invisibleCapabilities.yaml
  drivers/SmartThings/zigbee-thermostat/capabilities/valveCalibration.yaml
  drivers/SmartThings/zigbee-thermostat/fingerprints.yml
  drivers/SmartThings/zigbee-thermostat/profiles/thermostat-aqara.yml
  drivers/SmartThings/zigbee-thermostat/src/aqara/init.lua
  drivers/SmartThings/zigbee-thermostat/src/init.lua
  drivers/SmartThings/zigbee-thermostat/src/test/test_aqara_thermostat.lua
Labels: WWST

#1532 New Device (Matter Switch) Magic Cube DS001
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST, ATS

#1562 Aqara smart wall switch T1
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/aqara/init.lua
  drivers/SmartThings/zigbee-switch/src/aqara/multi-switch/init.lua
  tools/localizations/cn.csv
Labels: WWST

#1521 New Device (Matter Lock) Level Lock Plus
  drivers/SmartThings/matter-lock/fingerprints.yml
Labels: WWST

#1546 [Aqara] Presence Sensor FP2
  drivers/Aqara/aqara-presence-sensor/config.yml
  drivers/Aqara/aqara-presence-sensor/profiles/aqara-fp2-fallDetection.yml
  drivers/Aqara/aqara-presence-sensor/profiles/aqara-fp2-sleepMonitoring.yml
  drivers/Aqara/aqara-presence-sensor/profiles/aqara-fp2-zoneDetection.yml
  drivers/Aqara/aqara-presence-sensor/search-parameters.yml
  drivers/Aqara/aqara-presence-sensor/src/discovery.lua
  drivers/Aqara/aqara-presence-sensor/src/discovery_mdns.lua
  drivers/Aqara/aqara-presence-sensor/src/fields.lua
  drivers/Aqara/aqara-presence-sensor/src/fp2/api.lua
  drivers/Aqara/aqara-presence-sensor/src/fp2/device_manager.lua
  drivers/Aqara/aqara-presence-sensor/src/fp2/discovery_helper.lua
  drivers/Aqara/aqara-presence-sensor/src/init.lua
  drivers/Aqara/aqara-presence-sensor/src/lunchbox/init.lua
  drivers/Aqara/aqara-presence-sensor/src/lunchbox/rest.lua
  drivers/Aqara/aqara-presence-sensor/src/lunchbox/sse/eventsource.lua
  drivers/Aqara/aqara-presence-sensor/src/lunchbox/util.lua
  drivers/Aqara/aqara-presence-sensor/src/multipleZonePresence.lua
  drivers/Aqara/aqara-presence-sensor/src/selfSignedRootByAqaraLife.crt
  drivers/Aqara/aqara-presence-sensor/src/utils.lua
Labels: WWST

#1633 New Devices (Matter Switch) AiDot Orein St58CCT Bulbs
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST, ATS

#1513 Matter Sensor: add new device Heiman smoke sensor
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: WWST

#1502 Matter Sensor: Add HEIMAN smart CO sensor fingerprint
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: WWST

#1558 New Device (Matter Switch) ELEGRP MP10
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1503 Matter Sensor: Add Heiman Smart Smoke Sensor fingerprint
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: WWST

#1641 New Device (Matter Switch) Legrand Radiant Smart Switch
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST, ATS

#1192 New Devices (Z-Wave Switch): Shelly Switches
  drivers/SmartThings/zwave-switch/fingerprints.yml
  drivers/SmartThings/zwave-switch/src/multi-metering-switch/init.lua
  drivers/SmartThings/zwave-switch/src/multi-metering-switch/multi_metering_switch_configurations.lua
  drivers/SmartThings/zwave-switch/src/test/test_shelly_multi_metering_switch.lua
Labels: WWST

#1556 New Device (Matter Switch) Ledvance AC52861
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: do not merge, WWST

#1649 New Devices (Matter Switch) LetainPai Smart Switch(s)
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1650 New Device (Matter Lock) Level Bolt
  drivers/SmartThings/matter-lock/fingerprints.yml
Labels: WWST
