Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-02, with the labels that each got.

#1191 Add Smartvill Switch drivers
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/multi-switch-no-master/init.lua
Labels: do not merge, WWST

#1130 Added usage of datastore to save discovery cache
  drivers/SmartThings/jbl/src/discovery.lua
  drivers/SmartThings/jbl/src/init.lua
  drivers/SmartThings/jbl/src/jbl/api.lua
Labels: do not merge

#1209 Adding Zemismart Inline Module ZME2 Device
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: do not merge, WWST

#1163 matter-button: Change category for icon
  drivers/SmartThings/matter-button/profiles/button-battery.yml
  drivers/SmartThings/matter-button/profiles/button.yml
Labels: do not merge

#1195 [Eve]: Support for Eve Energy Outlet
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/src/eve-energy/init.lua
Labels: do not merge, WWST

#1231 New Device(Matter Switch) Cync Bulbs 1.01.060 and Outdoor Plug
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1221 LIFX Matter Pull Request
  drivers/SmartThings/matter-switch/fingerprints.yml
  drivers/SmartThings/matter-switch/profiles/light-level-ColorTemperature-1500-9000k.yml
Labels: WWST

#1034 Feature to Add Fingerprint for Tuo Temp Sensor
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: do not merge, WWST

#1241 New Device (Matter Switch) Eve Energy Switzerland 0x006A
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1242 New Device (Matter Switch) Eve Energy Outdoor 006B
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1145 Aqara Wireless Mini Switch T1
  drivers/SmartThings/zigbee-button/fingerprints.yml
  drivers/SmartThings/zigbee-button/src/aqara/init.lua
  drivers/SmartThings/zigbee-button/src/init.lua
  drivers/SmartThings/zigbee-button/src/test/test_aqara_button.lua
Labels: WWST
