Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2024-10, with the labels that each got.

#1661 New Device (Matter Switch) IM Pushbutton Module
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST, ATS

#1283 Add DeepSmart
  drivers/DeepSmart/deepsmart/config.yml
  drivers/DeepSmart/deepsmart/profiles/Ac.yml
  drivers/DeepSmart/deepsmart/profiles/Deepsmart-bridge.yml
  drivers/DeepSmart/deepsmart/profiles/Heater.yml
  drivers/DeepSmart/deepsmart/profiles/Newfan.yml
  drivers/DeepSmart/deepsmart/search-parameters.yml
  drivers/DeepSmart/deepsmart/src/commands.lua
  drivers/DeepSmart/deepsmart/src/config.lua
  drivers/DeepSmart/deepsmart/src/deepsmart/api.lua
  drivers/DeepSmart/deepsmart/src/deepsmart/devices.lua
  drivers/DeepSmart/deepsmart/src/deepsmart/dp2knx.lua
  drivers/DeepSmart/deepsmart/src/deepsmart/dpenum.lua
  drivers/DeepSmart/deepsmart/src/deepsmart/wisers.lua
  drivers/DeepSmart/deepsmart/src/discovery.lua
  drivers/DeepSmart/deepsmart/src/init.lua
  drivers/DeepSmart/deepsmart/src/lifecycles.lua
  drivers/DeepSmart/deepsmart/src/lunchbox/init.lua
  drivers/DeepSmart/deepsmart/src/lunchbox/rest.lua
  drivers/DeepSmart/deepsmart/src/lunchbox/sse/eventsource.lua
  drivers/DeepSmart/deepsmart/src/lunchbox/util.lua
  drivers/DeepSmart/deepsmart/src/selfSignedRoot.crt
  drivers/DeepSmart/deepsmart/src/ssdp.lua
  drivers/DeepSmart/deepsmart/src/utils.lua
Labels: do not merge, WWST

#1685 fp2: Change in Credential Management Approach
  drivers/Aqara/aqara-presence-sensor/src/discovery.lua
  drivers/Aqara/aqara-presence-sensor/src/init.lua
Labels: WWST

#1653 Add LeTianPai Smart Light Bulb fingerprint
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1722 New Device (Matter Switch) Cync BR30
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1717 fp2: add lowercase search parameter
  drivers/Aqara/aqara-presence-sensor/search-parameters.yml
Labels: WWST
