Repository SmartThingsCommunity/SmartThingsEdgeDrivers, pull requests merged in 2025-03, with the labels that each got.

#1508 Add zigbee-button for Vimar xx591 (Wall-mounted Remote Control)
  drivers/SmartThings/zigbee-button/fingerprints.yml
  drivers/SmartThings/zigbee-button/profiles/two-buttons-no-fw-update.yml
  drivers/SmartThings/zigbee-button/src/test/test_vimar_button.lua
  drivers/SmartThings/zigbee-button/src/zigbee-multi-button/init.lua
  drivers/SmartThings/zigbee-button/src/zigbee-multi-button/supported_values.lua
  drivers/SmartThings/zigbee-button/src/zigbee-multi-button/vimar/init.lua
Labels: WWST

#1927 add thirdreality TH sensor
  drivers/SmartThings/zigbee-humidity-sensor/fingerprints.yml
Labels: commit squashing required

#1975 Add device:Greentown Lock（SG20)
  drivers/SmartThings/zigbee-lock/fingerprints.yml
  tools/localizations/cn.csv
Labels: WWST

#1922 add support for generic zigbee multi-switch
  drivers/SmartThings/zigbee-switch/fingerprints.yml
  drivers/SmartThings/zigbee-switch/src/init.lua
  drivers/SmartThings/zigbee-switch/src/test/test_tuya_multi_switch.lua
  drivers/SmartThings/zigbee-switch/src/tuya-multi/init.lua
Labels: commit squashing required

#1995 New Devices (Matter Sensor + Matter Switch) 3 LG
  drivers/SmartThings/matter-sensor/fingerprints.yml
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#1873 New Device (Matter Switch) Shelly Plug PID 0001
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#2026 New Device (Matter Switch) Shelly Outdoor Plug 5 Gen3
  drivers/SmartThings/matter-switch/fingerprints.yml
Labels: WWST

#2021 New Device (Matter Sensor) LG Air Quality Sensor
  drivers/SmartThings/matter-sensor/fingerprints.yml
Labels: do not merge, WWST

#2034 New Device (Matter Lock) Level Lock Pro 0004
  drivers/SmartThings/matter-lock/fingerprints.yml
Labels: WWST

#1965 add thirdreality smart watering kit
  drivers/SmartThings/zigbee-watering-kit/config.yml
  drivers/SmartThings/zigbee-watering-kit/fingerprints.yml
  drivers/SmartThings/zigbee-watering-kit/profiles/watering-kit-thirdreality.yml
  drivers/SmartThings/zigbee-watering-kit/src/init.lua
  drivers/SmartThings/zigbee-watering-kit/src/test/test_thirdreality_watering_kit.lua
  drivers/SmartThings/zigbee-watering-kit/src/thirdreality/init.lua
  tools/localizations/cn.csv
Labels: commit squashing required, WWST
